package com.example.model;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

// Generated 11-05-2018 17:31:26 by Hibernate Tools 5.2.10.Final



/**
 * BlFlete generated by hbm2java
 */
@Entity
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property  = "bl", scope = BlFlete.class)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Table(name = "bl_flete", schema = "dbo")
public class BlFlete implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8595681458343278160L;
	private Bl bl;
	private String tipo;
	private String descripcion;



	
	@Id
	@ManyToOne(cascade = CascadeType.MERGE)
	@JoinColumn(name = "bl_nro_bl", nullable = true)
	public Bl getBl() {
		return this.bl;
	}

	public void setBl(Bl bl) {
		this.bl = bl;
	}

	@Column(name = "tipo", nullable = false, length = 15)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		if(descripcion!=null) {
		return this.descripcion.toUpperCase();	
		}else {
			return this.descripcion;
		}
		
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


}
