package com.example.model;

import com.example.config.Entidades;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

// Generated 11-05-2018 17:31:26 by Hibernate Tools 5.2.10.Final



/**
 * BlItemContenedorImo generated by hbm2java
 */
@Entity
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property  = "id", scope = BlItemContenedorImo.class)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Table(name = "bl_item_contenedor_imo", schema = "dbo")
public class BlItemContenedorImo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5862543807425220730L;
	private Integer id;
	private BlItemContenedor blItemContenedor=new BlItemContenedor();
	private String claseImo;
	private Integer numeroImo;

	

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequence_item_contenedor_imo")
	@SequenceGenerator(name = "sequence_item_contenedor_imo", sequenceName = "seq_item_contenedor_imo", allocationSize = 1, schema = "dbo", catalog = Entidades.CATALOGO_DB)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "bl_item_contenedor_id", nullable = false)
	public BlItemContenedor getBlItemContenedor() {
		return this.blItemContenedor;
	}

	public void setBlItemContenedor(BlItemContenedor blItemContenedor) {
		this.blItemContenedor = blItemContenedor;
	}

	@Column(name = "clase_imo", nullable = false, length = 4)
	public String getClaseImo() {
		return this.claseImo;
	}

	public void setClaseImo(String claseImo) {
		this.claseImo = claseImo;
	}

	@Column(name = "numero_imo", nullable = false)
	public Integer getNumeroImo() {
		return this.numeroImo;
	}

	public void setNumeroImo(Integer numeroImo) {
		this.numeroImo = numeroImo;
	}

}
