package com.example.model;

import com.example.config.Entidades;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

// Generated 11-05-2018 17:31:26 by Hibernate Tools 5.2.10.Final



/**
 * BlItemVehiculo generated by hbm2java
 */
@Entity
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property  = "id", scope = BlItemVehiculo.class)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Table(name = "bl_item_vehiculo", schema = "dbo")
public class BlItemVehiculo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8352767186568605666L;
	private int id;
	private BlItem blItem;
	private String modelo;
	private String idCajon;
	private String chassis;
	private String marca;
	private String observacion;

	

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequence_item_vehiculo")
	@SequenceGenerator(name = "sequence_item_vehiculo", sequenceName = "seq_item_vehiculo", allocationSize = 1, schema = "dbo", catalog = Entidades.CATALOGO_DB)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(cascade=CascadeType.MERGE)
	@JoinColumn(name = "bl_item_id", nullable = false)
	public BlItem getBlItem() {
		return this.blItem;
	}

	public void setBlItem(BlItem blItem) {
		this.blItem = blItem;
	}

	@Column(name = "modelo")
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "id_cajon", length = 10)
	public String getIdCajon() {
		return this.idCajon;
	}

	public void setIdCajon(String idCajon) {
		this.idCajon = idCajon;
	}

	@Column(name = "chassis", nullable = false, length = 30)
	public String getChassis() {
		return this.chassis;
	}

	public void setChassis(String chassis) {
		this.chassis = chassis;
	}

	@Column(name = "marca", nullable = false, length = 30)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		if(marca!=null) {
		this.marca = marca.toUpperCase();
		}else {
			this.marca = marca;
		}
	}

	@Column(name = "observacion")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		if(observacion!=null) {
			this.observacion = observacion.toUpperCase();
		}else {
			this.observacion = observacion;
		}
		
	}

}
