package com.example.model;
// Generated 11-05-2018 17:31:26 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.example.config.Entidades;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;



/**
 * BlItemContenedor generated by hbm2java
 */
@Entity
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property  = "id", scope = BlItemContenedor.class)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Table(name = "bl_item_contenedor", schema = "dbo")
public class BlItemContenedor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1746878722861443193L;
	private Integer id;
	private BlItem blItem=new BlItem();
	private String sigla;
	private String numero;
	private Character digito;
	private String tipoCnt;
	private String cntSo;
	private BigDecimal peso;
	private String valorIdOp;
	private String nombreOperador;
	private String estado;
	private Set<BlItemContenedorSello> blItemContenedorSellos = new HashSet<BlItemContenedorSello>(0);
	private Set<BlItemContenedorImo> blItemContenedorImos =new HashSet<BlItemContenedorImo>(0);



	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequence_item_cont")
	@SequenceGenerator(name = "sequence_item_cont", sequenceName = "seq_item_cont", allocationSize = 1, schema = "dbo", catalog = Entidades.CATALOGO_DB)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "bl_item_id", nullable = false)
	public BlItem getBlItem() {
		return this.blItem;
	}

	public void setBlItem(BlItem blItem) {
		this.blItem = blItem;
	}

	@Column(name = "sigla", length = 4)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "numero", length = 6)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "digito", length = 1)
	public Character getDigito() {
		return this.digito;
	}

	public void setDigito(Character digito) {
		this.digito = digito;
	}

	@Column(name = "tipo_cnt", length = 4)
	public String getTipoCnt() {
		return this.tipoCnt;
	}

	public void setTipoCnt(String tipoCnt) {
		this.tipoCnt = tipoCnt;
	}

	@Column(name = "cnt_so")
	public String getCntSo() {
		return this.cntSo;
	}

	public void setCntSo(String cntSo) {
		this.cntSo = cntSo;
	}

	@Column(name = "peso", nullable = false, precision = 16, scale = 3)
	public BigDecimal getPeso() {
		return this.peso;
	}

	public void setPeso(BigDecimal peso) {
		this.peso = peso;
	}

	@Column(name = "valor_id_op", length = 15)
	public String getValorIdOp() {
		return this.valorIdOp;
	}

	public void setValorIdOp(String valorIdOp) {
		this.valorIdOp = valorIdOp;
	}

	@Column(name = "nombre_operador", nullable = false)
	public String getNombreOperador() {
		return this.nombreOperador;
	}

	public void setNombreOperador(String nombreOperador) {
		if(nombreOperador!=null) {
			this.nombreOperador = nombreOperador.toUpperCase();
		}else {
			this.nombreOperador = nombreOperador;
		}
		
	}

	@Column(name = "estado", length = 10)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "blItemContenedor",orphanRemoval = true,cascade=CascadeType.ALL)
	public Set<BlItemContenedorSello> getBlItemContenedorSellos() {
		return this.blItemContenedorSellos;
	}

	public void setBlItemContenedorSellos(Set<BlItemContenedorSello> blItemContenedorSellos) {
		this.blItemContenedorSellos = blItemContenedorSellos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "blItemContenedor",orphanRemoval = true,cascade=CascadeType.ALL)
	public Set<BlItemContenedorImo> getBlItemContenedorImos() {
		return this.blItemContenedorImos;
	}

	public void setBlItemContenedorImos(Set<BlItemContenedorImo> blItemContenedorImos) {
		this.blItemContenedorImos = blItemContenedorImos;
	}

}
