package com.example.model;
// Generated 11-05-2018 17:31:26 by Hibernate Tools 5.2.10.Final

import java.util.Date;

import com.example.config.Entidades;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;



/**
 * BlReferencia generated by hbm2java
 */
@Entity
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property  = "id", scope = BlReferencia.class)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Table(name = "bl_referencia", schema = "dbo")
public class BlReferencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5455381537860688539L;
	private Integer id;
	private Bl bl;
	private String tipoReferencia;
	private String tipoDocumento;
	private String numero;
	private Date fecha;
	private String tipoIdEmisor;
	private String nacIdEmisor;
	private String valorIdEmisor;
	private String emisor;

	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequence_bl_referencia")
	@SequenceGenerator(name = "sequence_bl_referencia", sequenceName = "seq_bl_referencia", allocationSize = 1, schema = "dbo", catalog = Entidades.CATALOGO_DB)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(cascade=CascadeType.MERGE)
	@JoinColumn(name = "bl_nro_bl", nullable = false)
	public Bl getBl() {
		return this.bl;
	}

	public void setBl(Bl bl) {
		this.bl = bl;
	}

	@Column(name = "tipo_referencia", nullable = false, length = 10)
	public String getTipoReferencia() {
		return this.tipoReferencia;
	}

	public void setTipoReferencia(String tipoReferencia) {
		this.tipoReferencia = tipoReferencia;
	}

	@Column(name = "tipo_documento", nullable = false, length = 10)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "numero", nullable = false, length = 35)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Temporal(TemporalType.DATE)
	
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "tipo_id_emisor", length = 3)
	public String getTipoIdEmisor() {
		return this.tipoIdEmisor;
	}

	public void setTipoIdEmisor(String tipoIdEmisor) {
		this.tipoIdEmisor = tipoIdEmisor;
	}

	@Column(name = "nac_id_emisor", length = 2)
	public String getNacIdEmisor() {
		return this.nacIdEmisor;
	}

	public void setNacIdEmisor(String nacIdEmisor) {
		this.nacIdEmisor = nacIdEmisor;
	}

	@Column(name = "valor_id_emisor")
	public String getValorIdEmisor() {
		return this.valorIdEmisor;
	}

	public void setValorIdEmisor(String valorIdEmisor) {
		this.valorIdEmisor = valorIdEmisor;
	}

	@Column(name = "emisor")
	public String getEmisor() {
		return this.emisor;
	}

	public void setEmisor(String emisor) {
		if(emisor!=null) {
			this.emisor = emisor.toUpperCase();
		}else {
			this.emisor = emisor;
		}
		
	}

}
