package com.example.model;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

// Generated 11-05-2018 17:31:26 by Hibernate Tools 5.2.10.Final



/**
 * BlTransporte generated by hbm2java
 */
@Entity
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property  = "bl", scope = BlTransporte.class)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Table(name = "bl_transporte", schema = "dbo")
public class BlTransporte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2933179368797984818L;
	private Bl bl;
	private String sentidoOperacion;
	private String nombreNave;
	
	


	


	@Id
	@ManyToOne(cascade=CascadeType.MERGE)
	@JoinColumn(name = "bl_nro_bl", nullable = false, insertable = false, updatable = false)
	public Bl getBl() {
		return this.bl;
	}

	public void setBl(Bl bl) {
		this.bl = bl;
	}

	@Column(name = "sentido_operacion", nullable = false, length = 5)
	public String getSentidoOperacion() {
		return this.sentidoOperacion;
	}

	public void setSentidoOperacion(String sentidoOperacion) {
		this.sentidoOperacion = sentidoOperacion;
	}

	@Column(name = "nombre_nave", length = 50)
	public String getNombreNave() {
		return this.nombreNave;
	}

	public void setNombreNave(String nombreNave) {
		this.nombreNave = nombreNave;
	}

}
