package com.example.model;
// Generated 11-05-2018 17:31:26 by Hibernate Tools 5.2.10.Final

import java.util.Date;

import com.example.config.Entidades;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;


/**
 * BlTransbordo generated by hbm2java
 */
@Entity
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property  = "id", scope = BlTransbordo.class)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Table(name = "bl_transbordo", schema = "dbo")
public class BlTransbordo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7538366151748089948L;
	private Integer id;
	private Bl bl;
	private String codigoLugar;
	private String descripcionLugar;
	private Date fechaArribo;



	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequence_bl_transbordo")
	@SequenceGenerator(name = "sequence_bl_transbordo", sequenceName = "seq_bl_transbordo", allocationSize = 1, schema = "dbo", catalog = Entidades.CATALOGO_DB)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bl_nro_bl", nullable = false)
	public Bl getBl() {
		return this.bl;
	}

	public void setBl(Bl bl) {
		this.bl = bl;
	}

	@Column(name = "codigo_lugar", length = 5)
	public String getCodigoLugar() {
		return this.codigoLugar;
	}

	public void setCodigoLugar(String codigoLugar) {
		this.codigoLugar = codigoLugar;
	}

	@Column(name = "descripcion_lugar")
	public String getDescripcionLugar() {
		return this.descripcionLugar;
	}

	public void setDescripcionLugar(String descripcionLugar) {
		if(descripcionLugar!=null) {
			this.descripcionLugar = descripcionLugar.toUpperCase();
		}else {
			this.descripcionLugar = descripcionLugar;
		}
		
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_arribo", length = 23)
	public Date getFechaArribo() {
		return this.fechaArribo;
	}

	public void setFechaArribo(Date fechaArribo) {
		this.fechaArribo = fechaArribo;
	}

}
